CREATE DATABASE SalahTimesDB;
GO

USE SalahTimesDB;

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Role NVARCHAR(50) NOT NULL
);

CREATE TABLE Cities (
    Id INT PRIMARY KEY IDENTITY,
    CityName NVARCHAR(100) NOT NULL,
    Country NVARCHAR(100),
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    Timezone NVARCHAR(50) NOT NULL
);

CREATE TABLE SalahTimes (
    Id INT PRIMARY KEY IDENTITY,
    CityId INT FOREIGN KEY REFERENCES Cities(Id),
    Date DATE NOT NULL,
    Fajr TIME NOT NULL,
    Dhuhr TIME NOT NULL,
    Asr TIME NOT NULL,
    Maghrib TIME NOT NULL,
    Isha TIME NOT NULL,
    CreatedByUserId INT FOREIGN KEY REFERENCES Users(Id)
);
